# Generated by Django 3.1.3 on 2022-12-18 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20221218_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_content',
            new_name='choice',
        ),
    ]
